### ISSUE TITLE
Mansi keyboard not enabling, Word crashes

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-manager-windows#51]
Facts:
- Windows 10 computer, owned and managed by Helsinki University
- user has no admin rights
- Divvun Manager installed by IT, Mansi speller and keyboard installed
- after installation, no Mansi keyboard visible, Word crashes on startup
- running "enable Mansi keyboard", restart
- still no visible Mansi keyboard, Word still crashes
- debug log zip file created

**Comment by Trondtr** [comment]
When trying to install mansi on **mac** Divvun Manager does not rreopen after restart:

![kuva](https://user-images.githubusercontent.com/11891083/218085509-a27c3578-333a-4a75-bf49-ee5f94b926ba.png)

**Comment by Trondtr** [comment]
Aug 2024 Update: 
mns-Cyrl-RU (Mansi keyboard) installs nicely. It still has its problems (https://github.com/divvun/kbdi/issues/19), but this bug should be closed as not relevant any more, or it should probably have been rejected due to tha lack of admin rights. Well, DM, should not have been left hanging.
